-- RETORNA O ID DA WORKPLACE
SELECT W.ID 
FROM 
    TB_WORKPLACE W
    ,TB_STATION S 
WHERE 
    W.ID_STATION=S.ID 
    AND S.NAME = @STATION    
    AND W.NAME = @POSITION

-- RETORNA O ID DO TERMINAL
SELECT IdTerminal 
FROM TB_Terminal 
WHERE IdWorkstation = @ID_WORKSTATION

-- SELECIONA OS ULTIMOS LOGINS FEITOS NO POSTO
SELECT * FROM tEnter WHERE	L_TID=@ID_TERMINAL ORDER BY ID

-- VERIFICA TREINAMENTO DA PESSOA NO POSTO
SELECT * 
FROM 
    TB_PESSOAS P 
    ,TB_WORKPLACE_TR WTR 
WHERE 
    WTR.ID_PESSOA = P.ID 
    AND SSB = @SSB
    AND ID_WORKPLACE = @ID_WORKPLACE