-- RETORNA O ID DA WORKPLACE
SELECT W.ID 
FROM 
    TB_WORKPLACE W
    ,TB_STATION S 
WHERE 
    W.ID_STATION=S.ID 
    AND S.NAME = @STATION    
    AND W.NAME = @POSITION

-- RETORNA O ID DO TERMINAL
SELECT IdTerminal 
FROM TB_Terminal 
WHERE IdWorkstation = @ID_WORKSTATION

-- SELECIONA OS ULTIMOS LOGINS FEITOS NO POSTO
SELECT * FROM tEnter WHERE	L_TID=@ID_TERMINAL ORDER BY ID

-- VERIFICA TREINAMENTO DA PESSOA NO POSTO
SELECT * 
FROM 
    TB_PESSOAS P 
    ,TB_WORKPLACE_TR WTR 
WHERE 
    WTR.ID_PESSOA = P.ID 
    AND SSB = @SSB
    AND ID_WORKPLACE = @ID_WORKPLACE


-- PROCEDURES
CREATE PROCEDURE PROMOTION 
@OPR_SSB VARCHAR (6),
@LEADER_SSB VARCHAR (6),
@PREV_LEVEL tinyint,
@NEXT_LEVEL tinyint
as
INSERT INTO [LTS].[dbo].MATRIZ_PROMOTION 
(ID_PROMOTED, ID_LEADER, PREVIOUS_LEVEL, NEW_LEVEL)
VALUES(
	(SELECT ID FROM TB_PESSOAS WHERE SSB = @OPR_SSB),
	(SELECT ID FROM TB_PESSOAS WHERE SSB = @LEADER_SSB),
	@PREV_LEVEL,
	@NEXT_LEVEL
)